Repository autodesk-platform-services/aps-sdk-node, pull requests merged in 2024-07, with the labels that each got.

#34 Feature Upload function accepts memory stream as well
  oss/source/api/buckets-api.ts
  oss/source/api/objects-api.ts
  oss/source/custom-code/OssClient.ts
  oss/source/model/access.ts
  oss/source/model/batchsigneds3download-response.ts
  oss/source/model/batchsigneds3upload-response.ts
  oss/source/model/bucket-objects.ts
  oss/source/model/download-results.ts
  oss/source/model/region.ts
  oss/source/model/result.ts
Labels: enhancement

#37 Updated Oss sample
  samples/oss.ts
Labels: enhancement

#36 [Das 224] - Authentication SDK updates
  Authentication/source/api/token-api.ts
  Authentication/source/api/users-api.ts
  Authentication/source/custom-code/AuthenticationClient.ts
  Authentication/source/model/grant-type.ts
  Authentication/source/model/index.ts
  Authentication/source/model/introspect-token.ts
  Authentication/source/model/jwks-key.ts
  Authentication/source/model/jwks.ts
  Authentication/source/model/oidc-spec.ts
  Authentication/source/model/refresh-token.ts
  Authentication/source/model/response-type.ts
  Authentication/source/model/three-legged-token.ts
  Authentication/source/model/token-type-hint.ts
  Authentication/source/model/two-legged-token.ts
  Authentication/source/model/user-info-social-userinfo-list.ts
  Authentication/source/model/user-info.ts
  Authentication/source/package-lock.json
  Authentication/source/package.json
  samples/authentication.ts
  samples/package-lock.json
  samples/package.json
Labels: breaking

#41 Webhooks SDK - Bubble up error messages correctly
  samples/webhooks.ts
  webhooks/source/api/hooks-api.ts
  webhooks/source/api/tokens-api.ts
  webhooks/source/package.json
Labels: bug

#40 DAS-225 Admin SDK - Bubble up error messages correctly
  construction/accountadmin/source/api/account-users-api.ts
  construction/accountadmin/source/api/business-units-api.ts
  construction/accountadmin/source/api/companies-api.ts
  construction/accountadmin/source/api/project-users-api.ts
  construction/accountadmin/source/api/projects-api.ts
  construction/accountadmin/source/model/project-user-response.ts
  construction/accountadmin/source/model/project-user.ts
  construction/accountadmin/source/package.json
  samples/accountadmin.ts
Labels: bug
