Repository autodesk-platform-services/aps-sdk-node, pull requests merged in 2024-12, with the labels that each got.

#81 [DAS 311] - Changes for auth
  Authentication/source/api.ts
  Authentication/source/custom-code/index.ts
  Authentication/source/model/index.ts
  authentication/.gitignore
  authentication/.npmignore
  authentication/.prettierrc
  authentication/source/README.md
  authentication/source/api.ts
  authentication/source/api/tokenApi.ts
  authentication/source/api/usersApi.ts
  authentication/source/base.ts
  authentication/source/common.ts
  authentication/source/custom-code/authenticationClient.ts
  authentication/source/custom-code/index.ts
  authentication/source/index.ts
  authentication/source/model/grantType.ts
  authentication/source/model/index.ts
  authentication/source/model/introspectToken.ts
  authentication/source/model/jwks.ts
  authentication/source/model/jwksKey.ts
  authentication/source/model/oidcSpec.ts
  authentication/source/model/responseType.ts
  authentication/source/model/scopes.ts
  authentication/source/model/threeLeggedToken.ts
  authentication/source/model/tokenTypeHint.ts
  authentication/source/model/twoLeggedToken.ts
  authentication/source/model/userInfo.ts
  authentication/source/model/userInfoAddress.ts
  authentication/source/model/userInfoSocialUserinfoList.ts
  authentication/source/package-lock.json
  authentication/source/package.json
  authentication/source/tsconfig.esm.json
  authentication/source/tsconfig.json
  samples/authentication.ts
Labels: bug, documentation

#77 [DAS 310] - ACC Admin files rename camelcase
  construction/accountadmin/source/api.ts
  construction/accountadmin/source/api/accountUsersApi.ts
  construction/accountadmin/source/api/businessUnitsApi.ts
  construction/accountadmin/source/api/companiesApi.ts
  construction/accountadmin/source/api/projectUsersApi.ts
  construction/accountadmin/source/api/projectsApi.ts
  construction/accountadmin/source/custom-code/adminClient.ts
  construction/accountadmin/source/custom-code/index.ts
  construction/accountadmin/source/custom-code/utils.ts
  construction/accountadmin/source/model/accessLevels.ts
  construction/accountadmin/source/model/businessUnit.ts
  construction/accountadmin/source/model/businessUnitsRequest.ts
  construction/accountadmin/source/model/businessUnitsRequestPayload.ts
  construction/accountadmin/source/model/businessUnitsResponse.ts
  construction/accountadmin/source/model/companyImportResponse.ts
  construction/accountadmin/source/model/companyPatchPayload.ts
  construction/accountadmin/source/model/companyPayload.ts
  construction/accountadmin/source/model/companyResponse.ts
  construction/accountadmin/source/model/filterTextMatch.ts
  construction/accountadmin/source/model/index.ts
  construction/accountadmin/source/model/orFilters.ts
  construction/accountadmin/source/model/productAccess.ts
  construction/accountadmin/source/model/productKeys.ts
  construction/accountadmin/source/model/projectPatchResponse.ts
  construction/accountadmin/source/model/projectPayload.ts
  construction/accountadmin/source/model/projectPayloadProjectValue.ts
  construction/accountadmin/source/model/projectPayloadTemplate.ts
  construction/accountadmin/source/model/projectPayloadTemplateOptions.ts
  construction/accountadmin/source/model/projectPayloadTemplateOptionsField.ts
  construction/accountadmin/source/model/projectUser.ts
  construction/accountadmin/source/model/projectUserAccessLevels.ts
  construction/accountadmin/source/model/projectUserPayload.ts
  construction/accountadmin/source/model/projectUserPayloadProducts.ts
  construction/accountadmin/source/model/projectUserPhone.ts
  construction/accountadmin/source/model/projectUserProducts.ts
  construction/accountadmin/source/model/projectUserResponse.ts
  construction/accountadmin/source/model/projectUserRoles.ts
  construction/accountadmin/source/model/projectUsers.ts
  construction/accountadmin/source/model/projectUsersImportPayload.ts
  construction/accountadmin/source/model/projectUsersImportPayloadUsers.ts
  construction/accountadmin/source/model/projectUsersImportPayloadUsersProducts.ts
  construction/accountadmin/source/model/projectUsersImportResponse.ts
  construction/accountadmin/source/model/projectUsersUpdatePayload.ts
  construction/accountadmin/source/model/projectUsersUpdatePayloadProducts.ts
  construction/accountadmin/source/model/projects.ts
  construction/accountadmin/source/model/projectsPagination.ts
  construction/accountadmin/source/model/sortBy.ts
  construction/accountadmin/source/model/statusFilter.ts
  construction/accountadmin/source/model/userFields.ts
  construction/accountadmin/source/model/userImportResponse.ts
  construction/accountadmin/source/model/userPatchPayload.ts
  construction/accountadmin/source/model/userPatchStatus.ts
  construction/accountadmin/source/model/userPayload.ts
  construction/accountadmin/source/model/userSortBy.ts
  construction/accountadmin/source/package.json
  construction/accountadmin/source/tsconfig.json
  samples/accountadmin.ts
Labels: documentation

#79 [Das 309] Fixed Oss naming convention
  oss/source/api.ts
  oss/source/api/bucketsApi.ts
  oss/source/api/objectsApi.ts
  oss/source/custom-code/fileTransferConfigurations.ts
  oss/source/custom-code/index.ts
  oss/source/custom-code/ossClient.ts
  oss/source/custom-code/ossFileTransfer.ts
  oss/source/model/batchCompletedResults.ts
  oss/source/model/batchCompletedResultsParts.ts
  oss/source/model/batchcompleteuploadObject.ts
  oss/source/model/batchcompleteuploadObjectRequests.ts
  oss/source/model/batchcompleteuploadResponse.ts
  oss/source/model/batchsigneds3downloadObject.ts
  oss/source/model/batchsigneds3downloadObjectRequests.ts
  oss/source/model/batchsigneds3downloadResponse.ts
  oss/source/model/batchsigneds3uploadObject.ts
  oss/source/model/batchsigneds3uploadObjectRequests.ts
  oss/source/model/batchsigneds3uploadResponse.ts
  oss/source/model/batchsigneds3uploadResponseResultsValue.ts
  oss/source/model/bucket.ts
  oss/source/model/bucketObjects.ts
  oss/source/model/buckets.ts
  oss/source/model/bucketsItems.ts
  oss/source/model/completes3uploadBody.ts
  oss/source/model/createBucketsPayload.ts
  oss/source/model/createBucketsPayloadAllow.ts
  oss/source/model/createObjectSigned.ts
  oss/source/model/createSignedResource.ts
  oss/source/model/downloadResults.ts
  oss/source/model/downloadStatus.ts
  oss/source/model/index.ts
  oss/source/model/objectDetails.ts
  oss/source/model/objectFullDetails.ts
  oss/source/model/permission.ts
  oss/source/model/permissionAccess.ts
  oss/source/model/policyKey.ts
  oss/source/model/signeds3downloadResponse.ts
  oss/source/model/signeds3uploadResponse.ts
  oss/source/package.json
  oss/source/tsconfig.json
  samples/oss.ts
Labels: documentation

#85 [DAS 315] - Webhooks file renames
  webhooks/source/api.ts
  webhooks/source/api/hooksApi.ts
  webhooks/source/api/tokensApi.ts
  webhooks/source/custom-code/index.ts
  webhooks/source/custom-code/webhooksClient.ts
  webhooks/source/model/hook.ts
  webhooks/source/model/hookDetails.ts
  webhooks/source/model/hookDetailsScope.ts
  webhooks/source/model/hookPayload.ts
  webhooks/source/model/hooks.ts
  webhooks/source/model/hooksLinks.ts
  webhooks/source/model/index.ts
  webhooks/source/model/modifyHookPayload.ts
  webhooks/source/model/statusFilter.ts
  webhooks/source/model/statusRequest.ts
  webhooks/source/model/tokenPayload.ts
  webhooks/source/model/xAdsRegion.ts
  webhooks/source/package.json
  webhooks/source/tsconfig.json
Labels: documentation

#89 [Das 316] - Fixed upload and download method naming
  oss/source/custom-code/ossClient.ts
  oss/source/custom-code/ossFileTransfer.ts
  oss/source/package.json
  samples/oss.ts
Labels: bug
