Repository autodesk-platform-services/aps-sdk-node, pull requests merged in 2024-08, with the labels that each got.

#46 [DAS 256] - Authentication reorder refreshToken method to improve usability
  Authentication/source/custom-code/AuthenticationClient.ts
  samples/authentication.ts
  samples/package.json
Labels: enhancement

#48 [DAS 254] - Update ACC Admin models with the updated yaml
  construction/accountadmin/source/model/construction-type.ts
  construction/accountadmin/source/model/contract-type.ts
  construction/accountadmin/source/model/index.ts
  construction/accountadmin/source/model/language.ts
  construction/accountadmin/source/model/project-patch-response.ts
  construction/accountadmin/source/model/project-project-value.ts
  construction/accountadmin/source/model/project-status.ts
  construction/accountadmin/source/model/project.ts
  construction/accountadmin/source/model/user-role.ts
  construction/accountadmin/source/model/user-status.ts
  construction/accountadmin/source/model/user.ts
Labels: enhancement, breaking

#47 [DAS 240 ] - Remove Internal Endpoints
  oss/source/api/objects-api.ts
  oss/source/custom-code/OSSFileTransfer.ts
  oss/source/custom-code/OssClient.ts
  oss/source/model/create-signed-resource.ts
Labels: enhancement, breaking

#49 [DAS 260] - Add deprecated tag to region in specifyReferences
  modelderivative/source/model/specify-references-payload-references.ts
  modelderivative/source/model/specify-references-payload.ts
  modelderivative/source/package.json
Labels: documentation, enhancement

#50 [DAS-261] Define contributions guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation
